### ISSUE TITLE
Errors using Google GCP/CVM instance

### ISSUE THREAD

**Issue by patmantru** [ufcg-lsd/spire-amd-sev-snp-node-attestor#3]
I'm trying to use this code on a Google Confidential VM instance.  It has a Milan processor, but the TPM is actually a virtual TPM, 

Some issues I've run into:
- The EK response from the vTPM is in binary format, not PEM, so parsing it fails.  I'm supplying a PEM format using the ek_path parameter on the agent as a workaround.
- I'm getting 'ERRO[0010] Invalid argument: nodeattestor(amd_sev_snp): unable to validate TPM EK hash from report: EK SHA512 HASH is different from that provided by the attestation report' errors
- The attestation report is a different length (1539) than the code expects (1184).  I suspect this is causing the parsing of the report to fail, which leads to incorrect data being used to do the EK hash comparison
- Since it's a virtual TPM, the certificate materials are all based on Google roots, and not on AMD ones.  I've pulled the google certs mentioned in the ek_path file, and listed them on the server config in the cert_chains parameter.  I also disabled the CRL check.

Have you tried a Google CVM?  Suggestions on how to get this working?

Thanks!

**Comment by Daviiap** [comment]
Hi @patmantru! Can you check if there is your VM instance has the `/dev/sev-guest` char dev?

**Comment by patmantru** [comment]
That does not exist on my instance

**Comment by Daviiap** [comment]
Can you give more information about the instance (flavor, image type)?
The report in GCP isn't in the vTPM. We use the `/dev/sev-guest` driver to retrieve the report there. The vTPM is used on environments that use the SVSM module (eg. Azure and Baremetal).

**Comment by patmantru** [comment]
`modprobe: FATAL: Module sev-guest not found in directory /lib/modules/5.15.0-1062-gcp`

Ubuntu 20.04.6 LTS

![image](https://github.com/ufcg-lsd/spire-amd-sev-snp-node-attestor/assets/46453397/41f6b269-5663-493f-856c-d669fdad8bcd)

**Comment by Daviiap** [comment]
Running `sudo dmesg | grep -i snp` in the instance, what is the output?

**Comment by patmantru** [comment]
No matches

**Comment by Daviiap** [comment]
The output should be something like this:

![image](https://github.com/ufcg-lsd/spire-amd-sev-snp-node-attestor/assets/48532328/d61c4484-8ccb-4253-a85e-4e2304cb916c)

Trying a different image may work. (`ubuntu-2204-lts` images worked fine here).
Maybe you can verify the command used to launch the VM and see if you used the ``--confidential-compute-type=SEV_SNP``.

**Comment by patmantru** [comment]
Thank you, I will check the launch command to see about adding that, or changing the image

**Comment by patmantru** [comment]
THANK YOU!!!  The missing SEV-SNP was the problem all along.  Once I got that set up, the AMD certificates worked, the signatures were no longer based on google ones, which was a bonus.

I ended up having to provision a new machine to get the SEV-SNP support, here is the config if anyone else needs it:

`% gcloud compute instances create <your-system-name> \                                          
    --machine-type=n2d-standard-32 \
    --min-cpu-platform="AMD Milan" \
    --zone=us-central1-a \
    --confidential-compute-type=SEV_SNP \
    --maintenance-policy=TERMINATE \
    --image-family=ubuntu-2204-lts \
    --image-project=ubuntu-os-cloud \
    --project=<your google project>
`
